apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoazure-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demoazure
  template:
    metadata:
      labels:
        app: demoazure
    spec:
      containers:
      - name: demoazure
        image: demoazureacr.azurecr.io/demoazure:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: demoazure-service
spec:
  type: LoadBalancer
  selector:
    app: demoazure
  ports:
  - port: 80
    targetPort: 8080
