name: Build, Push to ACR, Deploy to AKS

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Azure CLI Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Set Docker image name
      id: image
      run: echo "tag=${{ secrets.ACR_LOGIN_SERVER }}/demoazure:${{ github.sha }}" >> $GITHUB_OUTPUT

    - name: Build Docker image
      run: |
        docker build -t ${{ steps.image.outputs.tag }} .

    - name: Push Docker image to ACR
      run: |
        az acr login --name ${{ secrets.ACR_LOGIN_SERVER }}
        docker push ${{ steps.image.outputs.tag }}

    - name: Set kubectl context
      uses: azure/aks-set-context@v3
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: MyAKSCluster
        resource-group: MyResourceGroup

    - name: Deploy to AKS
      run: |
        kubectl set image deployment/demoazure-deployment demoazure=demoazureacr.azurecr.io/demoazure:${{ github.sha }}
        kubectl rollout status deployment/demoazure-deployment
